<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1041774" started-at="2018-11-16T12:59:30Z" finished-at="2018-11-16T13:16:51Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="1041774" started-at="2018-11-16T12:59:30Z" finished-at="2018-11-16T13:16:51Z">
      <class name="Testcases.BillingPageScripts">
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:Testcases.BillingPageScripts@352ff4da]" name="beforeMethod" is-config="true" duration-ms="43871" started-at="2018-11-16T12:59:30Z" finished-at="2018-11-16T13:00:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="BillingPage_info_saveToMyAccount_validation()[pri:0, instance:Testcases.BillingPageScripts@352ff4da]" name="BillingPage_info_saveToMyAccount_validation" duration-ms="996914" started-at="2018-11-16T13:00:14Z" finished-at="2018-11-16T13:16:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at Reusables.MyAccountCCPageActions.verifySavedCreditDetailsFromCheckout(MyAccountCCPageActions.java:204)
at Testcases.BillingPageScripts.BillingPage_info_saveToMyAccount_validation(BillingPageScripts.java:167)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BillingPage_info_saveToMyAccount_validation -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Testcases.BillingPageScripts@352ff4da]" name="afterMethod" is-config="true" duration-ms="939" started-at="2018-11-16T13:16:50Z" finished-at="2018-11-16T13:16:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=BillingPage_info_saveToMyAccount_validation status=FAILURE method=BillingPageScripts.BillingPage_info_saveToMyAccount_validation()[pri:0, instance:Testcases.BillingPageScripts@352ff4da] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- Testcases.BillingPageScripts -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
