<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="372105" started-at="2018-10-30T05:20:42Z" finished-at="2018-10-30T05:26:55Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="372105" started-at="2018-10-30T05:20:42Z" finished-at="2018-10-30T05:26:55Z">
      <class name="Testcases.MyAccountScripts">
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="beforeMethod" is-config="true" duration-ms="52610" started-at="2018-10-30T05:20:42Z" finished-at="2018-10-30T05:21:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="myAcc_ShippingInfo_UIValidation()[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="myAcc_ShippingInfo_UIValidation" duration-ms="132850" started-at="2018-10-30T05:21:35Z" finished-at="2018-10-30T05:23:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myAcc_ShippingInfo_UIValidation -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="afterMethod" is-config="true" duration-ms="279" started-at="2018-10-30T05:23:48Z" finished-at="2018-10-30T05:23:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=myAcc_ShippingInfo_UIValidation status=SUCCESS method=MyAccountScripts.myAcc_ShippingInfo_UIValidation()[pri:0, instance:Testcases.MyAccountScripts@5db250b4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="beforeMethod" is-config="true" duration-ms="43453" started-at="2018-10-30T05:23:48Z" finished-at="2018-10-30T05:24:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="myAcc_ShippingInfo_addressPrePopulation_test()[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="myAcc_ShippingInfo_addressPrePopulation_test" duration-ms="12317" started-at="2018-10-30T05:24:32Z" finished-at="2018-10-30T05:24:44Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 3, Size: 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 3, Size: 1
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at Reusables.RegisterationPageActions.HomepageLoginSpecificAcc(RegisterationPageActions.java:183)
at Testcases.MyAccountScripts.myAcc_ShippingInfo_addressPrePopulation_test(MyAccountScripts.java:216)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myAcc_ShippingInfo_addressPrePopulation_test -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="afterMethod" is-config="true" duration-ms="505" started-at="2018-10-30T05:24:44Z" finished-at="2018-10-30T05:24:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=myAcc_ShippingInfo_addressPrePopulation_test status=FAILURE method=MyAccountScripts.myAcc_ShippingInfo_addressPrePopulation_test()[pri:0, instance:Testcases.MyAccountScripts@5db250b4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="beforeMethod" is-config="true" duration-ms="50862" started-at="2018-10-30T05:24:44Z" finished-at="2018-10-30T05:25:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="personalInformation_editing()[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="personalInformation_editing" duration-ms="16450" started-at="2018-10-30T05:25:35Z" finished-at="2018-10-30T05:25:52Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 2, Size: 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at Reusables.RegisterationPageActions.HomepageLogin_pinfoAcc(RegisterationPageActions.java:63)
at Testcases.MyAccountScripts.personalInformation_editing(MyAccountScripts.java:166)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- personalInformation_editing -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="afterMethod" is-config="true" duration-ms="473" started-at="2018-10-30T05:25:52Z" finished-at="2018-10-30T05:25:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=personalInformation_editing status=FAILURE method=MyAccountScripts.personalInformation_editing()[pri:0, instance:Testcases.MyAccountScripts@5db250b4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="beforeMethod" is-config="true" duration-ms="55281" started-at="2018-10-30T05:25:52Z" finished-at="2018-10-30T05:26:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="personalInformation_editingEmail()[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="personalInformation_editingEmail" duration-ms="6387" started-at="2018-10-30T05:26:48Z" finished-at="2018-10-30T05:26:54Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 2, Size: 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at Reusables.RegisterationPageActions.HomepageLogin_pinfoAcc(RegisterationPageActions.java:63)
at Testcases.MyAccountScripts.personalInformation_editingEmail(MyAccountScripts.java:185)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- personalInformation_editingEmail -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="afterMethod" is-config="true" duration-ms="578" started-at="2018-10-30T05:26:54Z" finished-at="2018-10-30T05:26:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=personalInformation_editingEmail status=FAILURE method=MyAccountScripts.personalInformation_editingEmail()[pri:0, instance:Testcases.MyAccountScripts@5db250b4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- Testcases.MyAccountScripts -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
